app1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from .views import home

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from .views import home, register, activate, logIn, logOut

app_name = 'users'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('login/', logIn, name='login'),
    path('logout/', logOut, name='logout'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
    path('activate/<str:uidb64>/<str:token>/',
         activate, name='activate'),
]

core/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser


# Profile manager
class ProfileManager(BaseUserManager):

    def _create_user(self, email, password, **extra_data):
        """
        Create and save a Profile with the given email and password.
        """
        if not email:
            raise ValueError("No valid email provided.")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_data)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_data):
        extra_data.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_data)

    def create_superuser(self, email, password, **extra_data):
        extra_data.setdefault("is_staff", True)
        extra_data.setdefault("is_superuser", True)

        if not extra_data.get("is_staff"):
            raise ValueError(
                "Superuser must have is_staff=True."
            )
        if not extra_data.get("is_superuser"):
            raise ValueError(
                "Superuser must have is_superuser=True."
            )

        return self._create_user(email, password, **extra_data)


# Profile user
class Profile(AbstractUser):
    username = models.CharField(max_length=8, unique=True)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    email = models.EmailField(max_length=128, unique=True)

    objects = ProfileManager()

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.username})'

users/forms.py
from logging import PlaceHolder
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import Profile


class RegistrationForm(UserCreationForm):
    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name', 'email')


class LogInForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'placeholder': 'ex: x123456'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'placeholder': '********'}))

core/views.py
from django.shortcuts import render

# Home view.
def home(request):
    return render(request, 'users/home.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from .forms import RegistrationForm, LogInForm
from .token import account_activation_token
from .models import Profile

# Home view
def home(request):
    return render(request, 'users/home.html') 


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('users/activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'users/confirm_email.html')
    else:
        form = RegistrationForm()
    return render(request, 'users/registration.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Profile.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Profile.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
    
    return render(request, 'users/email_confirmed.html')


def logIn(request):
    error = False
    if request.user.is_authenticated:
        return redirect('users:home')
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('users:home')
            else:
                error = True
    else:
        form = LogInForm()

    return render(request, 'users/login.html', {'form': form, 'error': error})


def logOut(request):
    logout(request)
    return redirect(reverse('users:login'))

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APP1 - {% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="page">
    {% block content %}
    <p>LAYOUT</p>
    {% endblock content %}
    </div>
</body>
</html>

users/templates/users/activation_email.html
{% autoescape off %}
Hi {{ user.first_name|capfirst }},
Please click on the link to confirm your registration.

{{ protocol }}://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

{% endautoescape %}
If the above link does not work, please copy and paste the URL into a new window of your browser.

Regards,
APP1 Team 

users/templates/users/confirm_email.html
{% extends 'layout.html' %}
{% block title %}Confirm you email address{% endblock title %}

{% block content %}
<p>We have sent you instructions to activate your account, if the provided email address is valid, you should receive them shortly.</p>
{% endblock content %}

users/templates/users/email_confirmed.html
{% extends 'layout.html' %}
{% block title %}Account activation{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<p>Thank you for your email confirmation. You are now logged in. Go to <strong><a href="{% url 'users:home' %}">HOME</a></strong>.</p>
{% else %}
<p>Your activation link is invalid!</p>
{% endif %}
{% endblock content %}

users/templates/users/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
  Welcome {{ user.first_name|capfirst }}!
  <p><a href="{% url 'users:password_change' %}">Change password</a></p>
  <p><a href="{% url 'users:logout' %}">Log Out</a></p>
{% else %}
  <p>Welcome. You are not logged in</p>
  <a href="{% url 'users:login' %}">Log In</a> |
  <a href="{% url 'users:register' %}">Register</a>
{% endif %}
{% endblock %}

users/templates/users/login.html
{% extends 'layout.html' %}
{% block title %}Log In{% endblock title %}
{% block content %}
{% if error %}
<p><strong>Invalid credentials. Please try again.</strong></p>
{% endif %}
<h3>Log In</h3>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Log In</button>
</form>
<p>Forgot your password? <a href="{% url 'users:password_reset' %}">Click here to reset your password.</a></p>
<p>New here? <strong><a href="{% url 'users:register' %}">Register</a></strong>.</p>
{% endblock content %}

users/templates/users/password_change.html
{% extends 'layout.html' %}
{% block title %}Change Password{% endblock title %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-7">
      <h2 class=" my-5">Change password</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.old_password.label_tag }}
          <input type="password" class="form-control {% if form.old_password.errors %}is-invalid{% endif %}"
            id="id_old_password" name="old_password" value='{{ form.old_password.value|default:"" }}'>
          {% if form.old_password.errors %}
          <div class="invalid-feedback">{{ form.old_password.errors }}</div>
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.new_password1.label_tag }}
          <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
            id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
          {% if form.new_password1.errors %}
          <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
          {% endif %}
          <small class="text-muted">{{ form.new_password1.help_text }}</small>
        </div>
        <div class="form-group">
          {{ form.new_password2.label_tag }}
          <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
            id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
          {% if form.new_password2.errors %}
          <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
          {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Change password</button>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/password_change_done.html
{% extends 'layout.html' %}
{% block title %}Password changed successfully{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="alert alert-success mt-5" role="alert">
        Your password has been changed successfully!
      </div>
      <a href="{% url 'users:home' %}" class="btn btn-secondary">Return to home page</a>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'layout.html' %}
{% block title %}Reset Password{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-4">
      <h2 class=" my-5">Password reset</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.email.label_tag }}
          <input type="email" class="form-control" id="id_email" name="email" value='{{ form.email.value|default:"" }}'>
        </div>
        <button type="submit" class="btn btn-primary">Reset Password</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'layout.html' %}
{% block title %}Password changed successfully{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="my-5">Password Changed successfully</h2>
      <p>
        Your password has been changed successfully. You may now proceed to
        <a href="{% url 'users:login' %}">log in.</a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'layout.html' %}
{% block title %}Set new password{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class=" my-5">Change password</h2>
      {% if validlink %}
      <div class="row">
        <form class="col-4" method="post">
          {% csrf_token %}
          <div class="form-group">
            {{ form.new_password1.label_tag }}
            <input type="password" class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
              id="id_new_password1" name="new_password1" value='{{ form.new_password1.value|default:"" }}'>
            {% if form.new_password1.errors %}
            <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.new_password2.label_tag }}
            <input type="password" class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
              id="id_new_password2" name="new_password2" value='{{ form.new_password2.value|default:"" }}'>
            {% if form.new_password2.errors %}
            <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">Change password</button>
        </form>
      </div>
      {% else %}
      <p>
        The password reset link was not valid, possibly because it has already been used,
        please request a <a href="{% url 'users:password_reset' %}">new password reset.</a>
      </p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'layout.html' %}
{% block title %}Reset Password Instructions{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class=" col-12">
      <h2 class="my-5">Password reset</h2>
      <p>
        We have sent you instructions for setting your password, if an account
        exists with the email you entered you should receive them shortly.
      </p>
      <p>
        If you haven't received an email, make sure you've entered the address you
        signed up with and check your spam folder.
      </p>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/password_reset_email.html
Hi {{ user.first_name|capfirst }},

To reset your password for the user {{ user.username }}, click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}


If the above link does not work, please copy and paste the URL into a new window of your browser.

Regards,
APP1 Team 

users/templates/users/registration.html
{% extends 'layout.html' %}
{% block title %}Registration{% endblock title %}
{% block content %}
<h3>Registration</h3>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</div>
{% endblock content %}